# Generated by Django 4.2.9 on 2024-01-23 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platerplotter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_rack_id', models.CharField(max_length=12)),
                ('laboratory_id', models.CharField(choices=[('yne', 'yne'), ('now', 'now'), ('eme', 'eme'), ('lnn', 'lnn'), ('lns', 'lns'), ('wwm', 'wwm'), ('sow', 'sow')], max_length=3)),
                ('glh_sample_consignment_number', models.CharField(max_length=50)),
                ('rack_acknowledged', models.BooleanField(default=False)),
                ('volume_checked', models.BooleanField(default=False)),
                ('disease_area', models.CharField(blank=True, choices=[('Cancer', 'Cancer'), ('Rare Disease', 'Rare Disease'), ('Mixed', 'Mixed')], max_length=12, null=True)),
                ('rack_type', models.CharField(blank=True, choices=[('Proband', 'Proband'), ('Family', 'Family'), ('Cancer Germline', 'Cancer Germline'), ('Tumour', 'Tumour'), ('Mixed', 'Mixed')], max_length=15, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Routine', 'Routine'), ('Urgent', 'Urgent'), ('Mixed', 'Mixed')], max_length=10, null=True)),
                ('gel_1004_csv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platerplotter.gel1004csv')),
            ],
        ),
    ]
