# Generated by Django 4.2.9 on 2024-01-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platerplotter', '0003_receivingrack_alter_sample_receiving_rack'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceivingRack',
        ),
    ]
