# Generated by Django 4.2.9 on 2024-02-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platerplotter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingrack',
            name='discarded',
            field=models.BooleanField(default=False),
        ),
    ]
