# Generated by Django 4.2.9 on 2024-02-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platerplotter', '0004_alter_holdingrackwell_holding_rack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingrackwell',
            name='holding_rack',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='platerplotter.holdingrack'),
            preserve_default=False,
        ),
    ]
