# Generated by Django 4.2.9 on 2024-02-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platerplotter', '0005_alter_holdingrackwell_holding_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingrackwell',
            name='assigned_time',
            field=models.DateTimeField(null=True),
        ),
    ]
