# Generated by Django 4.2.9 on 2024-09-23 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platerplotter', '0007_sample_non_issue_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='checked_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='discard_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='discarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='discarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
