services:
  platerplotter:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/platerplotter
    restart: always

    image: platerplotter:latest
    container_name: platerploter_container
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: db
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=platerplotter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data: